name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Needed for softprops/action-gh-release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build all binaries
        run: |
          mkdir -p dist

          platforms=(
            "linux/amd64"
            "darwin/amd64"
            "darwin/arm64"
            "windows/amd64"
          )

          for platform in "${platforms[@]}"; do
            IFS="/" read -r GOOS GOARCH <<< "$platform"
            output="dist/youtube-uploader-mcp-${GOOS}-${GOARCH}"
            [ "$GOOS" = "windows" ] && output="${output}.exe"

            echo "🔧 Building for $GOOS/$GOARCH"
            env GOOS=$GOOS GOARCH=$GOARCH \
              go build -ldflags "-s -w" -o "$output" .
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
